name: kaggle-house-prices
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - ipykernel
  - jupyter
  - pip
  - pip:
      - quarto-cli
